export const AuthConstants = {
  SIGNED_IN: 'SIGNED_IN',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EXISTS: 'USER_EXISTS',
};
