export const StatusConstants = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_API_KEY: 'INVALID_API_KEY',
  API_KEY_FREE_USAGE_EXCEEDED: 'API_KEY_FREE_USAGE_EXCEEDED',
  INVALID_OPERATION: 'INVALID_OPERATION',
};
